# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E6DXIvfP7lK_8XfdHuZE5XPBC9CuXop3
"""

def generate_spiral_matrix(n):
    #create an empty n*n matrix
    matrix= [[0] * n for _ in range (n)]
    num = 1
    top,bottom,left,right = 0,n-1,0,n-1

    while num <= n*n:
        for i in range (left,right +1):
            matrix[top][i]=num
            num+=1
        top +=1

        for i in range (top,bottom +1):
            matrix[i][right]=num
            num+=1
        right -=1

        for i in range (right,left -1,-1):
            matrix[bottom][i]=num
            num+=1
        bottom -=1

        for i in range (bottom,top -1,-1):
            matrix[i][left]=num
            num+=1
        left +=1

    return(matrix)

#genrating 4*4

matrix = generate_spiral_matrix(4)

for row in matrix:
    print(row)